### ISSUE TITLE
nav logo 被切

### ISSUE THREAD

**Issue by tw0517tw** [AlohaAI/AlohaAI.github.io#1]

**Comment by tw0517tw** [comment]
![default](https://cloud.githubusercontent.com/assets/1003146/20265259/fc3b2e48-aaaa-11e6-8c9e-4868a3cd1371.png)

**Comment by qshiwu** [comment]
[AlohaAI_Logo.svg.zip](https://github.com/AlohaAI/AlohaAI.github.io/files/589243/AlohaAI_Logo.svg.zip)

Try this one~
