### ISSUE TITLE
文案修正

### ISSUE THREAD

**Issue by qshiwu** [AlohaAI/AlohaAI.github.io#27]
修正部分以粗體字標示
-- 
- [ ] Engage Your Customers Everywhere, **Anytime**.
- [ ] **Emotional Connection Begins** with Sweet Conversations!
- [ ] Import existing customer service knowledge base to get basic **response**.
- [ ] One Click Publish: **Publish your AI on Facebook, Line, and WeChat as soon as it is trained**.
- [ ] Natural Language Understanding: **Built-in NLP engine enables your AI understand synonymous sentences.**
- [ ] Guiding conversation: **Aloha.AI helps your customers gather all the information they need.**（這句待韻如確認中）
- [ ] Intelligent Summary: **Aloha.AI summarizes conversation history before redirecting to human customer service.**

**Comment by tw0517tw** [comment]
how's （這句待韻如確認中） going?

**Comment by tw0517tw** [comment]
修完了
predicts the best response based on the context of the conversation to gather useful information from customers

**Comment by kpman** [comment]
#28
